apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::736153260724:role/eksctl-eksctl-demo-nodegroup-ng-dd119f6f
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
    rolearn: arn:aws:iam::736153260724:role/UdacityFlaskDeployCBKubectlRole
    username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-05T22:02:40Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1718"
  uid: e7921d52-5d2b-46da-93ba-779b1d655838
